export default {
  LIST_PASSWORD_PROCESSING: 'LIST_PASSWORD_PROCESSING',
  LIST_PASSWORD_SUCCESS: 'LIST_PASSWORD_SUCCESS',
  LIST_PASSWORD_ERROR: 'LIST_PASSWORD_ERROR',
  CREATE_PASSWORD_PROCESSING: 'CREATE_PASSWORD_PROCESSING',
  CREATE_PASSWORD_SUCCESS: 'CREATE_PASSWORD_SUCCESS',
  CREATE_PASSWORD_ERROR: 'CREATE_PASSWORD_ERROR',
  CREATE_PASSWORD_RESET: 'CREATE_PASSWORD_RESET',
  DELETE_PASSWORD_SUCCESS: 'DELETE_PASSWORD_SUCCESS'
}
